### ISSUE TITLE
Needs max file size and max runtime flags/switches 

### ISSUE THREAD

**Issue by gprime31** [projectdiscovery/alterx#12]
Subs.txt contains 15k lines
Results in 100+GB file with the enrich flag
So a max file output size and a max runtime switch would be great. Other than that the tool is awesome!!

**Comment by tarunKoyalwar** [comment]
@gprime31 , alterx already has limit flag to limit number of results
```console
   -limit int      limit the number of results to return (default 0)
```

**Comment by gprime31** [comment]
> @gprime31 , alterx already has limit flag to limit number of results
> 
> ```
>    -limit int      limit the number of results to return (default 0)
> ```

That's fine but how many results is say 52.4 GB? See the problem.

**Comment by tarunKoyalwar** [comment]
@gprime31 , on an average size of single subdomain(or single line)  is ~30 Bytes (or even less) . so for 52.4 GB it would be approx 1.746 Billion . not sure about the use case but I get your point and we will try to add option `-max-size`

**Comment by gprime31** [comment]
appreciate it.

**Comment by gprime31** [comment]
Did some testing and here are some rough values for reference:

	-	-limit 30000000 	= ~ 1.7GB
	-	-limit 100000000 	= ~ 5.4GB
	-	-limit 200000000	= ~ 11.5GB
	-	-limit 250000000	= ~ 14.7GB
	-	-limit 500000000	= ~ 29.3 GB
	-	-limit 1000000000 	= ~ 52.2GB

**Comment by ehsandeep** [comment]
@gprime31 this is now supported in latest release - https://github.com/projectdiscovery/alterx/releases/tag/v0.0.2
