### ISSUE TITLE
/tmp files remain after running Alterx

### ISSUE THREAD

**Issue by swdbo** [projectdiscovery/alterx#21]
## Current Behavior:

Hello,

I am currently running alterx on a Debian VPS, and I have encountered an issue where the VPS quickly runs out of disk space. It seems that temporary files created during the dedupe process are not being deleted. I believe this issue is related to the problem described in [ticket #3693](https://github.com/projectdiscovery/nuclei/issues/3693) on the projectdiscovery/nuclei GitHub repository.

## Expected Behavior:

- The temporary files should be cleaned up after the permutation command has finished.
- For debugging purposes, I suggest renaming the directory indicated [here](https://github.com/projectdiscovery/alterx/blob/31b13f1c0f9ee8757320c1b9c90d23419324faa5/internal/dedupe/leveldb.go#L20) to `alterx-report-*`.

## Steps To Reproduce:

To reproduce the issue, please follow these steps:

1. Run alterx using the command: `cat subdomains.txt | alterx -silent -enrich -limit 2000000`
2. Execute the command: `du -sh /tmp/nuclei-report-*` (Please note that some folders may be related to [real nuclei reports](https://github.com/projectdiscovery/alterx/blob/31b13f1c0f9ee8757320c1b9c90d23419324faa5/internal/dedupe/leveldb.go#L20))

Please let me know if you need more infos.

Regards,
swdb

**Comment by ehsandeep** [comment]
@swdbo this is now fixed in latest release - https://github.com/projectdiscovery/alterx/releases/tag/v0.0.2
