### ISSUE TITLE
Using Alterx as library is not generating any permutations

### ISSUE THREAD

**Issue by iamnihal** [projectdiscovery/alterx#47]
### Description

When using the alterx as a library to generate subdomain wordlists, it appears to be generating zero permutations. I'm using the example code provided in alterx's repository i.e., https://github.com/projectdiscovery/alterx/blob/main/examples/main.go

### Screenshot:
![image](https://github.com/projectdiscovery/alterx/assets/37813784/eb24d607-830a-4f30-b882-8f0471bcc0b6)

P.S.: I can't run with verbose mode as `Options` struct doesn't have the `Verbose` field.

**Comment by dogancanbakir** [comment]
Thanks for opening this issue. I updated the example code, see at https://github.com/projectdiscovery/alterx/pull/51.

**Comment by iamnihal** [comment]
Damn! I should've stared at code a little longer to find the real culprit. 😶‍🌫️ Thanks for your help @dogancanbakir!
